error C2374: 'i' : redefinition; multiple initialization
make MSVC 6.0 build again.
This code breaks:
for (int i=0;....
for (int i=0;....
use
int i;
for (i=0;...
for (i=0;...
instead ;-)